services:
    _defaults:
        autowire: true
        public: false

    Chaplean\Bundle\KanbanizeApiClientBundle\Api\KanbanizeApiV1:
        arguments:
            $client: '@eight_points_guzzle.client.kanbanize_api_v1'
            $urlPrefix: '%chaplean_kanbanize_api_v1.url%'
            $apikey: '%chaplean_kanbanize_api.apikey%'

    Chaplean\Bundle\KanbanizeApiClientBundle\Api\KanbanizeApiV2:
        arguments:
            $client: '@eight_points_guzzle.client.kanbanize_api_v2'
            $urlPrefix: '%chaplean_kanbanize_api_v2.url%'
            $apikey: '%chaplean_kanbanize_api.apikey%'
